### PR TITLE
Add ViewComponent >2.35.0 vars to the exclusion list

### PR DESCRIPTION
**Pull request by r3trofitted**
This PR should fix the problems with ViewComponent 2.35.0 (see #111).

Unfortunately, I couldn't find a way to add tests for this fix. Instead, I've just reviewed the list of newly prefixed variables and added those that were already in the `Rendering` module under their former name.

It's a bit rough, but as far as I can tell, it works.

### CODE REVIEW

**Comment by jbbarth** [comment]
@r3trofitted don't you think we could filter out any instance variable starting with `@__vc_` ? I think ViewComponent intends to prefix instance variables private to their implementation with this. So something more generic would be more future proof ? Or maybe you think it's too complicated/risky ?

**Comment by latortuga** [comment]
@r3trofitted thanks for the contribution!

I agree with @jbbarth that filtering by the variable prefix seems like a great strategy. Can you update this to try that?

**Comment by r3trofitted** [comment]
@latortuga Sure, here you go! 

To be honest, I'm a bit on the fence about this strategy, though. Keeping a registry of variables to be excluded is tedious and brittle, but since I know very little about both Motion and View Component, I was feeling more confortable staying close to the existing logic. But if you're confident that Motion will never ever need to include one of VC's “private” variables in the dump, then, filtering on the prefix is definitely a better approach. I leave it to you!

**Comment by latortuga** [comment]
I've been noodling on this for a few days and I can't decide what I think. @alecdotninja or @Gmfholley can you weigh in on this?

**Comment by bert-mccutchen** [comment]
> @latortuga Sure, here you go!
> 
> To be honest, I'm a bit on the fence about this strategy, though. Keeping a registry of variables to be excluded is tedious and brittle, but since I know very little about both Motion and View Component, I was feeling more confortable staying close to the existing logic. But if you're confident that Motion will never ever need to include one of VC's “private” variables in the dump, then, filtering on the prefix is definitely a better approach. I leave it to you!

I relate to this deeply. It's a tad bit infuriating not being able to assign an instance variable that I _don't_ want in the state. For example if I want to load a `User` record from the database, I don't want to have to load it every time I use it, so I naturally want to assign it to an instance variable. However, then it will apply the entire model to the state, even though I don't want it to.

I think a beneficial approach would be to define what instance variables you want to apply to the state. Here's an example of what I am thinking:
```ruby
class ProductSelector < ViewComponent::Base
  include Motion::Component

  attr_reader :product_id, :products

  # This would tell motion to only include `product_id` when dumping the component's attributes.
  serializes :product_id

  map_motion :select_product

  def initialize(product_id:)
    @product_id = product_id
    @products = Product.all
  end

  def select_product(event)
    @product_id = event.target.value.to_i
  end
end
```

```erb
<div class="product-selector">
  <%= select_tag 'products', options_from_collection_for_select(products, :id, :name, product_id), data: { motion: 'change->select_product' } %>
</div>
```

**Comment by bert-mccutchen** [comment]
I've created a pull request with an implementation for inclusive dumping attributes: https://github.com/unabridged/motion/pull/118

**Pull request merged**
